---
# perform some basic setup that should be standard for any new system
# like configuring ntp
- hosts: all
  become: True
  pre_tasks:
  - name: "update cache"
    apt:
      update_cache: True
  roles:
    - role: geerlingguy.ntp
