---
- hosts: consulhosts
  become: True
  vars:
    dnsmasq_consul_postfix: consul
    dnsmasq_consul_host: 127.0.0.1
    dnsmasq_consul_port: 8600
    dnsmasq_consul_rev_servers: []
    dnsmasq_upstream_nameservers:
    - '8.8.8.8'
    - '8.8.4.4'
  tasks:
  - name: "ensure dnsmasq is installed"
    package:
      name: "dnsmasq"
      state: present
  
  - name: "copy config for consul dns resolution"
    template:
      src: "10-consul.j2"
      dest: "/etc/dnsmasq.d/10-consul"
    notify: restart dnsmasq

  - name: insert nameservers
    lineinfile:
      path: /etc/resolv.dnsmasq.conf
      line: "nameserver {{ item }}"
      create: True
    with_items: "{{ dnsmasq_upstream_nameservers }}"

  - name: modify dnsmasq.conf
    lineinfile:
      path: /etc/dnsmasq.conf
      regexp: "{{ item.regexp }}"
      insertafter: "{{ item.insertafter }}"
      line: "{{ item.line }}"
    with_items:
    - { regexp: '^resolv-file=', insertafter: "#resolv-file", line: 'resolv-file=/etc/resolv.dnsmasq.conf'}
    notify: restart dnsmasq
    
  handlers:
  - name: restart dnsmasq
    service:
      name: dnsmasq
      state: restarted
      enabled: True
