- hosts: dockerhosts
  pre_tasks:
  - name: "try to download key via http"
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
    become: True
  roles:
    - role: angstwad.docker_ubuntu
      docker_apt_channel: edge # only until we have stable version available for ubuntu 18.04
      daemon_json:
        log-level: debug
        dns: ["{{ansible_host}}","8.8.8.8", "8.8.4.4"]

#      pip_version_docker_compose: 1.9.0
#      docker_dns: ["{{ansible_docker0.ipv4.address}}","8.8.8.8", "8.8.4.4"]
#      docker_storage_driver: overlay2
#      docker_log_driver: gelf
#      docker_log_opts:
#        gelf-address: tcp://192.168.56.22:12201
      become: True
  tasks:
  - name: restart dnsmasq
    service:
      name: dnsmasq
      state: restarted
    become: True
