- hosts: grafana-servers
  gather_facts: False
  vars:
    cert_src_dir: /home/vagrant/pki
    cert_dest_dir: /etc/grafana/certs
    ca_cert_file: ca.pem
    keycloak_cert_file: keycloak.service.consul.pem
  become: True
  tasks:
  - name: Create Grafana user
    user:
      name: grafana
      shell: /usr/sbin/nologin
      state: present
  - name: "create config dir"
    file:
      path: "/etc/grafana"
      state: directory
      mode: "0755"
  - name: "create certs dir"
    file:
      path: "/etc/grafana/certs"
      state: directory
      mode: "0755"
  - name: copy ca cert
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
    - { src: "{{ cert_src_dir }}/{{ ca_cert_file}}", dest: "{{ cert_dest_dir }}/{{ ca_cert_file }}"}
    - { src: "{{ cert_src_dir }}/{{ keycloak_cert_file}}", dest: "{{ cert_dest_dir }}/{{ keycloak_cert_file }}"}
  - name: "create sqllite dir"
    file:
      path: "/var/lib/grafana"
      state: directory
      mode: "0700"
  - name: "Create Grafana config"
    template:
      src: grafana.ini.j2
      dest: /etc/grafana/grafana.ini
  - name: Start Grafana Container
    docker_container:
      name: grafana
      image: grafana/grafana
      published_ports:
      - "3000:3000"
      volumes:
      - "/var/lib/grafana:/var/lib/grafana"
      - "/etc/grafana:/etc/grafana"
      - "{{ cert_dest_dir }}:/etc/ssl/certs"
      env:
        GF_SECURITY_ADMIN_PASSWORD: secret
      restart_policy: unless-stopped
      restart: True
  - name: register grafana
    consul:
      service_name: grafana
      service_port: 3000
      tags:
      - urlprefix-grafana.nomad.cluster/
      http: "http://{{ ansible_host }}:3000/"
      interval: 30s