# elasticsearch cluster (used by graylog / gitlab)
- import_playbook: playbooks/es.yml
# mongodb replica set (used by graylog)
- import_playbook: playbooks/mongodb.yml
# install the acutal log management software
- import_playbook: playbooks/graylog.yml
