- hosts: nomadhosts
  become: True
  pre_tasks:
  - name: "get nomad vault token"
    set_fact:
      nomad_token: "{{lookup('file', '/etc/vault/nomad_token.json')| from_json}}"
  roles:
    - role: rattermeyer.nomad
      nomad_iface: 'enp0s8'
      nomad_enable_syslog: True
      nomad_tls_enable: True
      nomad_tls_src_dir: /home/vagrant/pki
      nomad_tls_ca_crt: "ca.pem"
      nomad_tls_verify_server_hostname: True
      nomad_tls_verify_client: True
      nomad_vault: True
      nomad_vault_ca_file: "/etc/nomad/ssl/ca.pem"
      nomad_vault_token: "{{nomad_token.auth.client_token}}"
      nomad_version: "0.8.3"
      nomad_sha256sum: "c7faaee8fad0f6a74df01b9283253ee565f85791adca1d6a38462e0387dee175"
      become: True
- hosts: nomad_nodes
  tasks:
  - name: install opendjk8
    become: True
    package:
      name: openjdk-8-jre
