---
- hosts: openldap-servers
  become: True

  vars:
    server_uri: "ldapi:///"

  pre_tasks:
  - name: install dependency
    apt:
      name: python-jmespath
    become: True

  - name: check for default settings
    stat:
      path: "/etc/default/slapd"
    register: st_slapd

  roles:
  - role: local.openldap
    openldap_schemas:
      - core
      - cosine
      - nis
      - inetorgperson
      - rfc2739
    openldap_bases:
      - rootdn: cn=admin
        suffix: dc=opendp,dc=org
        indexes:
          - [ "uid,uidNumber,gidNumber,memberUID", "pres,eq" ]
          
  post_tasks:
  - name: Make sure we have a parent entry for users
    ldap_entry:
      dn: "{{ item.dn }}"
      objectClass: "{{ item.objectclass }}"
      attributes: "{{ item.attributes }}"
      bind_dn: cn=admin,dc=opendp,dc=org
      bind_pw: secret
      server_uri: "{{server_uri}}"
    with_items:
    - { dn: "dc=opendp,dc=org",
        objectclass: ["dcObject", "organization"],
        attributes: {
          o: opendp project,
          dc: opendp 
        }
      }
    - { dn: "ou=users,dc=opendp,dc=org",
        objectclass: ["organizationalUnit"],
        attributes: {
          ou: users 
        }
      }
    - { dn: "ou=groups,dc=opendp,dc=org",
        objectclass: ["organizationalUnit"],
        attributes: {
          ou: users 
        }
      }
    - { 
        dn: "uid=alice,ou=users,dc=opendp,dc=org",
        objectclass: ["inetOrgPerson", "organizationalPerson", "person", "top"],
        attributes: {
          uid: alice,
          cn: "alice springs",
          sn: "springs",
          mail: "alice.springs@opendp.local",
          userPassword: '{SSHA}CEO5svZIGFMKGrAPsXnWwK418E3ZZWMcwFNZmg==' # alice
        }
      }
    - { 
        dn: "uid=bob,ou=users,dc=opendp,dc=org",
        objectclass: ["inetOrgPerson", "organizationalPerson", "person", "top"],
        attributes: {
          uid: bob,
          cn: "bob andrews",
          sn: "andrews", 
          mail: "bob.andrews@opendp.local",
          userPassword: "{SSHA}p9AEzCP/uCHV3Szpw/Hhbq9CRV18CVxL" # bob 
        }
      }
    - { 
        dn: "uid=nick,ou=users,dc=opendp,dc=org",
        objectclass: ["inetOrgPerson", "organizationalPerson", "person", "top"],
        attributes: {
          uid: nick,
          cn: "nick elback",
          sn: "elback", 
          mail: "nick.elback@opendp.local",
          userPassword: "{SSHA}DpJ+anPij+H/6PWEaLsYMgvmo5n2umPA" # nick
        }
      }
    - { 
        dn: "uid=gandalf,ou=users,dc=opendp,dc=org",
        objectclass: ["inetOrgPerson", "organizationalPerson", "person", "top"],
        attributes: {
          uid: gandalf,
          cn: "gandalf white",
          sn: "white", 
          mail: "gandalf.white@opendp.local",
          userPassword: "{SSHA}N38uSoaeuhc9NsGHwjy/GGU8NXgr9qTR" # gandalf
        }
      }
    - { 
        dn: "uid=victor,ou=users,dc=opendp,dc=org",
        objectclass: ["inetOrgPerson", "organizationalPerson", "person", "top"],
        attributes: {
          uid: victor,
          cn: "victor visitor",
          sn: "visitor", 
          mail: "victor.visitor@opendp.local",
          userPassword: "{SSHA}TPs96o80TKjTYSbGP0Mn29U6XgGLbda/" # nick
        }
      }
    - { 
        dn: "cn=developers,ou=groups,dc=opendp,dc=org",
        objectclass: ["groupOfNames"],
        attributes: {
          cn: developers,
          member: "uid=bob,ou=users,dc=opendp,dc=org"
        }
      }
    - { 
        dn: "cn=cdengineers,ou=groups,dc=opendp,dc=org",
        objectclass: ["groupOfNames"],
        attributes: {
          cn: cdengineers,
          member: "uid=nick,ou=users,dc=opendp,dc=org"
        }
      }
    - { 
        dn: "cn=dbadmins,ou=groups,dc=opendp,dc=org",
        objectclass: ["groupOfNames"],
        attributes: {
          cn: dbadmins,
          member: "uid=alice,ou=users,dc=opendp,dc=org"
        }
      }
    - { 
        dn: "cn=visitors,ou=groups,dc=opendp,dc=org",
        objectclass: ["groupOfNames"],
        attributes: {
          cn: visitors,
          member: "uid=victor,ou=users,dc=opendp,dc=org"
        }
      }
    - { 
        dn: "cn=cluster-admins,ou=groups,dc=opendp,dc=org",
        objectclass: ["groupOfNames"],
        attributes: {
          cn: visitors,
          member: "uid=gandalf,ou=users,dc=opendp,dc=org"
        }
      }
    tags: post_task

  - name: ensure users in groups
    ldap_attr:
      dn: "{{ item.dn }}"
      name: "{{ item.name }}" 
      values: "{{ item.ldap_values }}"
      state: exact
      bind_dn: "cn=admin,dc=opendp,dc=org"
      bind_pw: secret
    with_items:
    - {
      dn: "cn=developers,ou=groups,dc=opendp,dc=org",
      name: "member",
      ldap_values: ["uid=bob,ou=users,dc=opendp,dc=org", "uid=alice,ou=users,dc=opendp,dc=org"]
    }
    tags: post_task

  - include: openldap_tls.yml
    tags: tls
    

