---
- hosts: controller
  roles:
  - role: local.pki
    pki_servers:
      - cname: consul.server1.localdomain
        include_localhost: True
        sans:
          - consul.server1.localdomain
        altips:
        - 192.168.56.21
      - cname: consul.server2.localdomain
        include_localhost: True
        sans:
          - consul.server2.localdomain
        altips:
        - 192.168.56.22
      - cname: consul.server3.localdomain
        include_localhost: True
        sans:
          - consul.server3.localdomain
        altips:
        - 192.168.56.23
      - cname: server.global.nomad
        sans:
          - nomad.service.consul
        include_localhost: True
        altips:
        - 192.168.56.21
        - 192.168.56.22
        - 192.168.56.23
      - cname: graylog.service.consul
        include_localhost: True
        altips:
        - 192.168.56.21
        - 192.168.56.22
        - 192.168.56.23
      - cname: client.global.nomad
        include_localhost: True
        altips:
        - 192.168.56.24
        - 192.168.56.25
      - cname: vault.service.consul
        include_localhost: True
        sans:
        - "*.vault.service.consul"
        altips:
        - 192.168.56.21
        - 192.168.56.22
        - 192.168.56.23
      - cname: registry.service.consul
        include_localhost: True
        altips:
        - 192.168.56.21
        - 192.168.56.22
        - 192.168.56.23
      - cname: fabio.service.consul
        include_localhost: True
        sans:
        - "*.fabio.service.consul"
        - "*.nomad.cluster"
    pki_clients:
    - consul-worker1
    - consul-worker2
    - consul-worker3
    - consul-controller
