- hosts: postgresql-master
  vars:
    postgresql_version: 10
    postgresql_cluster_name: odp
    postgresql_conf_directory: "/etc/postgresql/{{postgresql_version}}/{{postgresql_cluster_name}}"
    postgresql_admin_user: postgres
    postgresql_service_user: "{{ postgresql_admin_user }}"
    postgresql_service_userid: 1046
    postgresql_service_group: "{{ postgresql_admin_user }}"
    postgresql_service_groupid: "{{ postgresql_service_userid }}"
    postgresql_varlib_directory_name: "postgresql"
    postgresql_data_directory: "/var/lib/{{ postgresql_varlib_directory_name }}/{{postgresql_version}}/{{postgresql_cluster_name}}"

  tasks:
  - name: Create Postgres group
    group:
      name: "{{ postgresql_service_group }}"
      gid: "{{ postgresql_service_groupid }}"
    become: True

  - name: Create Postgres user
    user:
      name: "{{ postgresql_service_user }}"
      uid: "{{ postgresql_service_userid }}"
      shell: /usr/sbin/nologin
      state: present
      group: "{{ postgresql_service_group }}"
    become: True

  - name: Create directories
    file:
      path: "{{ postgresql_data_directory }}"
      owner: "{{ postgresql_service_user }}"
      group: "{{ postgresql_service_group }}"
      state: directory
    become: True

  - name: PostgreSQL | start docker container
    docker_container:
      name: "postgres"
      image: "postgres:{{postgresql_version}}"
      network_mode: host
      restart_policy: on-failure
      restart_retries: 5
      volumes:
      - "/etc/passwd:/etc/passwd:ro"
      - "{{ postgresql_data_directory }}:/var/lib/postgresql/data"
      env:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'post123gres'
    become: True
  
