- hosts: prometheus-servers
  become: True
  tasks:
  - name: "create config dir"
    file:
      path: "/etc/prometheus"
      state: directory
      mode: "0755"
  - name: "create prometheus config"
    template:
      src: prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
  # TODO see angstwad. Need to decide if we check pre-requisites here, then we need some logic
  - name: "ensure python docker-py is installed"
    pip:
      name: docker
  - name: "start container"
    docker_container:
      name: prometheus
      image: "prom/prometheus"
      ports:
      - "9090:9090"
      volumes:
      - "/etc/prometheus:/etc/prometheus"
      - "/etc/consul/ssl/ca.pem:/etc/consul/ssl/ca.pem"
      - "/etc/nomad/ssl:/etc/nomad/ssl"
      restart_policy: unless-stopped
      restart: True
