- hosts: localhost
  tasks:
#  - name: test module
#    nomad_job:
#      inline_data:
#      enforce_index:
#      job_modify_index:
#      job_id: // job_id
#      mode: // update, dispatch, stop
#      payload: // in case of dispatch

  - name: test module dispatch
    nomad_job:
      # nomad_host: 127.0.0.1
      # nomad_port: 4646
      # nomad_token:
      # cert_path:
      # secure: True / False
      inline_data: 
        Job:
          ID: example
          Name: example
          Type: service
          Datacenters:
          - dc1
          TaskGroups:
          - Name: cache
            Count: 1
            Tasks:
            - Name: redis
              Driver: docker
              User: ''
              Config:
                image: redis:3.2
                port_map:
                - db: 6379
              Services:
              - Id: ''
                Name: global-redis-check
                Tags:
                - global
                - cache
                PortLabel: db
                AddressMode: ''
                Checks:
                - Id: ''
                  Name: alive
                  Type: tcp
                  Command: ''
                  Path: ''
                  Protocol: ''
                  PortLabel: ''
                  AddressMode: ''
                  Interval: 10000000000
                  Timeout: 2000000000
                  InitialStatus: ''
                  TLSSkipVerify: false
                  Method: ''
              Resources:
                CPU: 500
                MemoryMB: 256
                Networks:
                - Device: ''
                  CIDR: ''
                  IP: ''
                  MBits: 10
                  DynamicPorts:
                  - Label: db
                    Value: 0
              Leader: false
              ShutdownDelay: 0
              KillSignal: ''
            RestartPolicy:
              Interval: 300000000000
              Attempts: 10
              Delay: 25000000000
              Mode: delay
            EphemeralDisk:
              SizeMB: 300
          Update:
            MaxParallel: 1
            MinHealthyTime: 10000000000
            HealthyDeadline: 180000000000
            AutoRevert: false
            Canary: 0
          