---
- hosts: vault_servers
  tasks:
  - name: ensure pip is installed
    package:
        name: python-pip
  - name: install hvac
    pip:
        name: hvac
  
  
  - name: get vault status
    hashivault_status:
      url: https://192.168.56.21:8200
      ca_cert: "/etc/vault/ssl/ca.pem"
    register: 'vault_status'
    tags: vault_status
    run_once: True
  
  - debug:
      msg: "{{vault_status}}"
    tags: vault_status
  
  - block:
    - name: "get client token"
      set_fact:
        tmp_data: "{{lookup('file', '/etc/vault/keys.json')| from_json}}"
    - name: "extract client token"
      set_fact:
        client_token: "{{tmp_data.root_token}}"
    - hashivault_secret_list:
        url: https://192.168.56.21:8200
        ca_cert: "/etc/vault/ssl/ca.pem"
        token: "{{client_token}}"
      register: 'hashivault_secret_list'
      tags: secret_list
    - name: enable postgres secrets backend
      hashivault_secret_enable:
        name: "database/odp"
        backend: "database"
        url: https://192.168.56.21:8200
        ca_cert: "/etc/vault/ssl/ca.pem"
        token: "{{client_token}}"
      tags:
      - vault
    when: vault_status.status.sealed == False
    run_once: True
