- name: "lookup keys"
  slurp:
    src: /etc/vault/keys.json
  register: vault_keys
- set_fact:
    vault_init: "{{vault_keys['content'] | b64decode }}"
- debug:
    msg: "{{ groups['vault_servers']|map('extract', hostvars, 'ansible_host')|list }}"
- name: "unseal vault"
  hashivault_unseal:
    keys: "{{vault_init.keys_base64 | join(' ')}}"
    url: "https://{{item}}:8200"
  with_items: "{{ groups['vault_servers']|map('extract', hostvars, 'ansible_host')|list }}"
