---
- hosts: controller
  tasks:
  - name: "install tools"
    become: True
    package:
      name: "{{ item }}"
    with_items:
    - tar
    - unzip

- import_playbook: playbooks/pki.yml
  when: pki_create == True

# base images often have us mirrors configured.
# that results in bad latency for other parts of the world
# downloading packges is quite slow
- import_playbook: playbooks/fix-mirror.yml
# perform basic installation of packages that should be present
# on all nodes, e.g. ntp       
- import_playbook: playbooks/base-config.yml
# on ubuntu swap limit support is not enabled by default.
# this can be activated by changing GRUB CMD line
- import_playbook: playbooks/update-grub.yml
# install service discovery and K/V store as a base component
- import_playbook: playbooks/servicediscovery.yml
# and install a secrets management system and configure it
- import_playbook: playbooks/vaultserver.yml
- import_playbook: playbooks/vaultsetup.yml
# elasticsearch cluster (used by graylog / gitlab)
- import_playbook: playbooks/es.yml
# mongodb replica set (used by graylog)
- import_playbook: playbooks/mongodb.yml
# install the acutal log management software
- import_playbook: playbooks/graylog.yml
# now we can install docker
# TODO configure docker to use graylog directly
- import_playbook: playbooks/docker.yml

# deploy s3 compatible backend (e.g. for docker registry)
- import_playbook: playbooks/minio.yml

# now we can install our clusterscheduler (nomad)
- import_playbook: playbooks/clusterscheduler.yml
# and deploy monitoring systems
- import_playbook: playbooks/monitoring.yml
- import_playbook: playbooks/nomad-ui.yml
