---
- name: configure postgres
  import_tasks: configure.yml
  tags: [postgresql, postgresql-configure]

- name: install postgres
  import_tasks: install.yml
  tags: [postgresql, postgresql-install]

# create users, databases
# and assign users privileges on databases
- name: create users
  include_tasks: users.yml
  tags: [postgresql, postgresql-users]
- name: create databases
  include_tasks: databases.yml
  tags: [postgresql, postgresql-databases]
- name: grant user privileges
  include_tasks: users_privileges.yml
  tags: [postgresql, postgresql-user_privileges]
