# defaults are debian-compatible
---
# default: change4me
# you can generate a password hash using `slappasswd -h {SSHA} -s change4me`
# TODO: check if this is used at all
openldap_rootpw: "{SSHA}hNScvQAWLLcWjE6EdUqxdNOsZboxV4TD"
openldap_confdir: /etc/ldap
openldap_user: openldap
openldap_group: openldap

# under ubuntu, database directory is only allowed to be under
# /var/lib/ldap
# this is defined under /etc/apparmor.d/usr.sbin.slapd
# changes to this directory would require changes to this file as well
openldap_datadir: /var/lib/ldap
openldap_db_engine: mdb
openldap_db_maxsize: 1073741824
openldap_modsdir: /usr/lib/ldap
openldap_slapd_service_name: slapd
openldap_slapd_exec: /usr/sbin/slapd
openldap_slapd_pidfile: /var/run/slapd/slapd.pid
openldap_slapd_argsfile: /var/run/slapd/slapd.args
openldap_slapd_ports:
- 389
- 636

#openldap_slave_rid: 0
openldap_schmas:
  - core
  - cosine
  - inetorgperson
  - nis
